# Generated by Django 5.2.3 on 2025-08-04 23:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubRepository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("github_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("html_url", models.URLField()),
                ("clone_url", models.URLField()),
                ("language", models.CharField(blank=True, max_length=50)),
                ("stars_count", models.IntegerField(default=0)),
                ("forks_count", models.IntegerField(default=0)),
                ("owner", models.CharField(max_length=255)),
                ("is_private", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("last_indexed", models.DateTimeField(blank=True, null=True)),
                (
                    "indexed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indexed_repos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-stars_count", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GitHubCodeExample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("file_path", models.TextField()),
                ("code_content", models.TextField()),
                ("language", models.CharField(max_length=50)),
                ("concepts", models.JSONField(blank=True, default=list)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_examples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_examples",
                        to="github_integration.githubrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-upvotes", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GitHubSearchResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", models.TextField()),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("repositories", "Repositories"),
                            ("code", "Code"),
                            ("commits", "Commits"),
                            ("issues", "Issues"),
                            ("users", "Users"),
                        ],
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=50)),
                ("results_data", models.JSONField(default=dict)),
                ("total_count", models.IntegerField(default=0)),
                ("search_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="github_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserGitHubProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_username", models.CharField(blank=True, max_length=255)),
                ("github_token", models.CharField(blank=True, max_length=255)),
                ("preferred_languages", models.JSONField(blank=True, default=list)),
                ("search_history", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "favorite_repos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorited_by",
                        to="github_integration.githubrepository",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GitHubFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.TextField()),
                ("filename", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("sha", models.CharField(max_length=40)),
                ("size", models.IntegerField()),
                ("download_url", models.URLField()),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("language", models.CharField(blank=True, max_length=50)),
                (
                    "last_fetched",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="github_integration.githubrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["repository", "path"],
                "unique_together": {("repository", "path")},
            },
        ),
    ]
